import { BatchTestSummary } from "./batch-tester";

export const DEMO_BATCH_DATA: BatchTestSummary = {
  totalProcessed: 50,
  overallSuccessRate: 96,
  overallSuccessCount: 48,
  totalU16Avoided: 16,
  totalFallbacksTriggered: 19,
  averageLatencyMs: 345,
  railDistribution: [
    {
      method: "aadhaar_otp",
      name: "Aadhaar-OTP UPI",
      count: 21,
      percentage: 44,
      isReal: false,
    },
    {
      method: "razorpay_link",
      name: "Razorpay Payment Link",
      count: 19,
      percentage: 40,
      isReal: true,
    },
    {
      method: "upi_collect",
      name: "UPI Collect Request",
      count: 6,
      percentage: 12,
      isReal: false,
    },
    {
      method: "account_ifsc_qr",
      name: "Account + IFSC QR",
      count: 2,
      percentage: 4,
      isReal: false,
    },
  ],
  bankStats: [
    {
      bankName: "State Bank of India",
      ifscPrefix: "SBIN",
      bankType: "PSU",
      total: 8,
      successes: 8,
      successRate: 100,
      u16RejectionsEncountered: 5,
      fallbacksTriggered: 4,
      winningRails: {
        aadhaar_otp: 4,
        razorpay_link: 3,
        upi_collect: 1,
        account_ifsc_qr: 0,
      },
    },
    {
      bankName: "Punjab National Bank",
      ifscPrefix: "PUNB",
      bankType: "PSU",
      total: 5,
      successes: 5,
      successRate: 100,
      u16RejectionsEncountered: 4,
      fallbacksTriggered: 3,
      winningRails: {
        aadhaar_otp: 2,
        razorpay_link: 2,
        upi_collect: 1,
        account_ifsc_qr: 0,
      },
    },
    {
      bankName: "Bank of Baroda",
      ifscPrefix: "BARB",
      bankType: "PSU",
      total: 4,
      successes: 4,
      successRate: 100,
      u16RejectionsEncountered: 3,
      fallbacksTriggered: 2,
      winningRails: {
        aadhaar_otp: 2,
        razorpay_link: 2,
        upi_collect: 0,
        account_ifsc_qr: 0,
      },
    },
    {
      bankName: "Canara Bank",
      ifscPrefix: "CNRB",
      bankType: "PSU",
      total: 4,
      successes: 3,
      successRate: 75,
      u16RejectionsEncountered: 2,
      fallbacksTriggered: 2,
      winningRails: {
        aadhaar_otp: 2,
        razorpay_link: 1,
        upi_collect: 0,
        account_ifsc_qr: 0,
      },
    },
    {
      bankName: "Union Bank of India",
      ifscPrefix: "UBIN",
      bankType: "PSU",
      total: 3,
      successes: 3,
      successRate: 100,
      u16RejectionsEncountered: 2,
      fallbacksTriggered: 1,
      winningRails: {
        aadhaar_otp: 1,
        razorpay_link: 2,
        upi_collect: 0,
        account_ifsc_qr: 0,
      },
    },
    {
      bankName: "HDFC Bank",
      ifscPrefix: "HDFC",
      bankType: "PRIVATE",
      total: 6,
      successes: 6,
      successRate: 100,
      u16RejectionsEncountered: 0,
      fallbacksTriggered: 1,
      winningRails: {
        aadhaar_otp: 2,
        razorpay_link: 3,
        upi_collect: 1,
        account_ifsc_qr: 0,
      },
    },
    {
      bankName: "ICICI Bank",
      ifscPrefix: "ICIC",
      bankType: "PRIVATE",
      total: 5,
      successes: 5,
      successRate: 100,
      u16RejectionsEncountered: 0,
      fallbacksTriggered: 1,
      winningRails: {
        aadhaar_otp: 2,
        razorpay_link: 2,
        upi_collect: 1,
        account_ifsc_qr: 0,
      },
    },
    {
      bankName: "Axis Bank",
      ifscPrefix: "UTIB",
      bankType: "PRIVATE",
      total: 4,
      successes: 4,
      successRate: 100,
      u16RejectionsEncountered: 0,
      fallbacksTriggered: 1,
      winningRails: {
        aadhaar_otp: 2,
        razorpay_link: 1,
        upi_collect: 1,
        account_ifsc_qr: 0,
      },
    },
    {
      bankName: "Kotak Mahindra Bank",
      ifscPrefix: "KKBK",
      bankType: "PRIVATE",
      total: 3,
      successes: 3,
      successRate: 100,
      u16RejectionsEncountered: 0,
      fallbacksTriggered: 1,
      winningRails: {
        aadhaar_otp: 1,
        razorpay_link: 1,
        upi_collect: 1,
        account_ifsc_qr: 0,
      },
    },
    {
      bankName: "Yes Bank",
      ifscPrefix: "YESB",
      bankType: "PRIVATE",
      total: 3,
      successes: 3,
      successRate: 100,
      u16RejectionsEncountered: 0,
      fallbacksTriggered: 1,
      winningRails: {
        aadhaar_otp: 1,
        razorpay_link: 1,
        upi_collect: 0,
        account_ifsc_qr: 1,
      },
    },
    {
      bankName: "Paytm Payments Bank",
      ifscPrefix: "PYTM",
      bankType: "PAYMENT_BANK",
      total: 3,
      successes: 3,
      successRate: 100,
      u16RejectionsEncountered: 0,
      fallbacksTriggered: 1,
      winningRails: {
        aadhaar_otp: 1,
        razorpay_link: 1,
        upi_collect: 0,
        account_ifsc_qr: 1,
      },
    },
    {
      bankName: "India Post Payments Bank",
      ifscPrefix: "IPOS",
      bankType: "PAYMENT_BANK",
      total: 2,
      successes: 1,
      successRate: 50,
      u16RejectionsEncountered: 0,
      fallbacksTriggered: 1,
      winningRails: {
        aadhaar_otp: 1,
        razorpay_link: 0,
        upi_collect: 0,
        account_ifsc_qr: 0,
      },
    },
  ],
  sampleTraces: [
    {
      requestId: "req_demo_01_sbin",
      bankName: "State Bank of India",
      accountMasked: "•••8291",
      winningRail: "Aadhaar-OTP UPI Activation",
      status: "COMPLETED",
      attemptsCount: 1,
      u16Hit: false,
    },
    {
      requestId: "req_demo_02_punb",
      bankName: "Punjab National Bank",
      accountMasked: "•••4012",
      winningRail: "Razorpay Smart Payment Link",
      status: "COMPLETED",
      attemptsCount: 2,
      u16Hit: true,
    },
    {
      requestId: "req_demo_03_hdfc",
      bankName: "HDFC Bank",
      accountMasked: "•••9182",
      winningRail: "Razorpay Smart Payment Link",
      status: "COMPLETED",
      attemptsCount: 1,
      u16Hit: false,
    },
    {
      requestId: "req_demo_04_sbin",
      bankName: "State Bank of India",
      accountMasked: "•••3319",
      winningRail: "Razorpay Smart Payment Link",
      status: "COMPLETED",
      attemptsCount: 2,
      u16Hit: true,
    },
    {
      requestId: "req_demo_05_barb",
      bankName: "Bank of Baroda",
      accountMasked: "•••7721",
      winningRail: "Aadhaar-OTP UPI Activation",
      status: "COMPLETED",
      attemptsCount: 1,
      u16Hit: false,
    },
    {
      requestId: "req_demo_06_icic",
      bankName: "ICICI Bank",
      accountMasked: "•••0051",
      winningRail: "UPI Collect Request (VPA Push)",
      status: "COMPLETED",
      attemptsCount: 1,
      u16Hit: false,
    },
    {
      requestId: "req_demo_07_ubin",
      bankName: "Union Bank of India",
      accountMasked: "•••6294",
      winningRail: "Razorpay Smart Payment Link",
      status: "COMPLETED",
      attemptsCount: 2,
      u16Hit: true,
    },
    {
      requestId: "req_demo_08_cnrb",
      bankName: "Canara Bank",
      accountMasked: "•••1942",
      winningRail: "Aadhaar-OTP UPI Activation",
      status: "COMPLETED",
      attemptsCount: 1,
      u16Hit: false,
    },
    {
      requestId: "req_demo_09_pytm",
      bankName: "Paytm Payments Bank",
      accountMasked: "•••8810",
      winningRail: "Account + IFSC QR (Last Resort)",
      status: "COMPLETED",
      attemptsCount: 1,
      u16Hit: false,
    },
    {
      requestId: "req_demo_10_sbin",
      bankName: "State Bank of India",
      accountMasked: "•••4429",
      winningRail: "Aadhaar-OTP UPI Activation",
      status: "COMPLETED",
      attemptsCount: 1,
      u16Hit: false,
    },
    {
      requestId: "req_demo_11_utib",
      bankName: "Axis Bank",
      accountMasked: "•••7315",
      winningRail: "UPI Collect Request (VPA Push)",
      status: "COMPLETED",
      attemptsCount: 1,
      u16Hit: false,
    },
    {
      requestId: "req_demo_12_kkbk",
      bankName: "Kotak Mahindra Bank",
      accountMasked: "•••5521",
      winningRail: "Razorpay Smart Payment Link",
      status: "COMPLETED",
      attemptsCount: 1,
      u16Hit: false,
    },
    {
      requestId: "req_demo_13_yesb",
      bankName: "Yes Bank",
      accountMasked: "•••2190",
      winningRail: "Account + IFSC QR (Last Resort)",
      status: "COMPLETED",
      attemptsCount: 1,
      u16Hit: false,
    },
    {
      requestId: "req_demo_14_punb",
      bankName: "Punjab National Bank",
      accountMasked: "•••9912",
      winningRail: "Razorpay Smart Payment Link",
      status: "COMPLETED",
      attemptsCount: 2,
      u16Hit: true,
    },
    {
      requestId: "req_demo_15_ipos",
      bankName: "India Post Payments Bank",
      accountMasked: "•••6630",
      winningRail: "Aadhaar-OTP UPI Activation",
      status: "COMPLETED",
      attemptsCount: 1,
      u16Hit: false,
    },
  ],
};
